FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy project
COPY . .

# Start development server
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"] 